# Generated by Django 2.2.7 on 2019-11-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', models.FloatField(max_length=10)),
                ('result', models.CharField(max_length=10)),
            ],
        ),
    ]
