# Generated by Django 2.2.7 on 2019-11-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cal',
            new_name='Calate',
        ),
    ]
